from ..models import ConfigSchema


def config_file():
    template = ConfigSchema(
        name="my config",
        developer="your name here",
        description="this is the template autodoc config file generated by us",
        ignore=[".env", "venv", ".gitignore"],
    )
    print("api hit")
    result = template.toJsonTemplate()

    return result
