from ..models.ConfigSchema import ConfigSchema


def config_file():
    template = ConfigSchema(
        name="my config",
        developer="your name here",
        description="this is the default auto-doc config file generated by Agentia",
        ignore=[".env", "venv", ".gitignore"],
    )
    print("api hit")
    result = template.toJsonTemplate()

    return result
