from google.adk.agents.llm_agent import Agent
from google.adk.tools.agent_tool import AgentTool

instuction = """ You are the DocumentationWriterAgent. 
Input:
- The original JSON payload containing:
  - app_name
  - description
  - filetree
  - code (filename → content)
- Access the previous analysis using {semantic_understanding} which contains the semantic analysis.

Your job:
1. Generate full, beautiful, human-readable documentation.Your job:
1. Generate full, beautiful,human-readable documentation.
2. Include:
   - A project README with app name and description (table of contents, install details, usage details, things like that)
   - Example usage if enough context is available and your confidence in correct usage is 100%.
3. Format the output consistently (Markdown MANDATORY).
4. Maintain accuracy: do not hallucinate code behavior or add information not present in the semantic_understanding.
5. Organize the documentation logically, using sections, headings, and tables where appropriate. 
   Add Graphs, tables, and charts in markdown where appropriate. 

    Return ONLY the markdown text directly, not wrapped in JSON.


Rules:
- Do not modify the original code.
- Do not summarize too briefly; include enough detail for a developer to understand usage.
- Preserve naming conventions and function signatures as given in the semantic understanding.
- Ensure the documentation is clear, readable, and professional.
- DO NOT GO OVER EVERY SINGLE FUNCTION, FUNCTION SIGNATURE, AND SO ON...MODEL YOUR README BASED OFF OF INDUSTRY STANDARDS FOR OPEN SOURCE PROJECTS. ONLY INCLUDE WHAT IS STANDARD
- AFTER THE APP NAME HEADING AT THE VERY TOP OF THE FILE, YOU MUST ADD  
  [![Documented by Autodoc](https://img.shields.io/badge/Documented%20by-Autodoc-blue?style=for-the-badge&logo=readthedocs)](https://github.com/AliArgonaut/autodoc-cli) DIRECTLY UNDER IT. THIS
  IS THE BADGE SHOWING THAT THIS DOCUMENTATION WAS GENERATED BY AUTODOC AND IT MUST BE IN EVERY GENERATED README.
"""

Docs_Writer_Agent = Agent(
    model='gemini-2.5-flash-lite',
    name='Docs_Writer_Agent',
    description='an agent that generates markdown documentation according to recieved information',
    instruction=instuction,
    output_key="final_docs"
)

Docs_Writer_Agent_Tool = AgentTool(Docs_Writer_Agent)
