package services

import (
	"cli/services/utils"
	"fmt"
)

func GenerateService() {

	cwd := utils.GetCWD()
	name := utils.GetName(cwd)

	entries[] := utils.GetIgnoredFilesArrayService(cwd) //want this to return an array of strings with ignored files

	//what if we did buildtree service but it takes in entries generated by GetIgnoredFilesArrayService?
	tree := utils.BuildTreeService(cwd, name, entries[])
	fmt.Println(tree)
}
