package services

import (
	"fmt"
	"io"
	"net/http"
	"os"
)

func AutodocInitService() {
	fmt.Println("initializing autodoc code services...")
	resp, err := http.Get("http://localhost:8000/api/init")
	if err != nil {
		fmt.Println("ERROR: failed to init...couldn't retrieve config template from backend")
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("ERROR: failed to parse config template generated by backend")
	}
	bodyString := string(body)

	GenerateConfigInPath(bodyString)
	fmt.Println("SUCCESS: autodoc_config.json generated!")
	fmt.Println("ADVICE: don't forget to update your config file, it'll save tokens!")

}

// add code that creates the file from response body here
func GenerateConfigInPath(content string) {
	defaultName := "autodoc_config.json"
	err := os.WriteFile(defaultName, []byte(content), 0644)
	if err != nil {
		fmt.Println("ERROR: error writing file")
	}

}
