package services

import (
	"fmt"
	"io"
	"net/http"
)

func AutodocInitService() {
	fmt.Println("frontend auto doc service init")
	resp, err := http.Get("http://localhost:8000/api/init")
	if err != nil {
		fmt.Println("failed to init...couldn't retrieve config template from backend")
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("failed to parse config template generated by backend")
	}
	bodyString := string(body)
	fmt.Println(bodyString)
}

//add code that creates the file from response body here
